const Images = {
  ImgBack: require('../imgs/rewind.png'),
  ImgClock: require('../imgs/clock.png'),
  ImgCamera: require('../imgs/upload-photo.png'),
  ImgProfile: require('../imgs/profile-pic.png'),
  ImgUser: require('../imgs/user.png'),
  ImgEmail: require('../imgs/email.png'),
  ImgGender: require('../imgs/gender.png'),
  ImgFlag: require('../imgs/flag.png'),
  ImgPhone: require('../imgs/phone.png'),
  ImgBag: require('../imgs/bag.png'),
  ImgLocation: require('../imgs/location.png'),
  ImgEarth: require('../imgs/earth.png'),
  ImgBuilding: require('../imgs/building.png'),
  ImgCalendar: require('../imgs/calender.png'),
  ImgCap: require('../imgs/cap.png'),
  ImgCertificate: require('../imgs/cetificate.png'),
  ImgDoctor: require('../imgs/doctor.png'),
  ImgContact: require('../imgs/contact.png'),
  ImgLage: require('../imgs/lage.png'),
  ImgDelete: require('../images/delete.png'),
  ImgRefresh: require('../imgs/refresh.png'),
  ImgRadioUncheck: require('../imgs/ic_radio_uncheck.png'),
  ImgRadioCheck: require('../imgs/ic_radio_check.png'),
  ImgMenuRoundVertical: require('../imgs/ic_menu_round_vertical.png'),
  ImgDownArrow: require('../imgs/ic_down_arrow.png'),
  ImgVideoCall: require('../imgs/ic_video_call.png'),
};
export default Images;